name: Run FreeRoam Script

on:
  push:
    branches: [ main ]
  # Optionally, you can schedule the workflow:
  # schedule:
  #   - cron: '0 * * * *'  # runs every hour

jobs:
  run-freeRoam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run FreeRoam Script
        env:
          FLEXIROAM_USERNAME: ${{ secrets.FLEXIROAM_USERNAME }}
          FLEXIROAM_PASSWORD: ${{ secrets.FLEXIROAM_PASSWORD }}
        run: python Flexiroam_FreePlan.py

